# workflow.py

"""
Auto-generate the GitHub Actions workflows for a package.

Reads the package and its `pyproject.toml`, then writes `ci.yml` (the gate) and `publish.yml`
(PyPI over OIDC, waiting on the gate). Nothing in either file is hand-edited: regenerate.

Example:
  >>> from workflow import generate
  >>> generate("xaeian")

CLI:
  py workflow.py xaeian
  py workflow.py xaeian -o .github/workflows
"""

import sys, tomllib
from dataclasses import dataclass
from xaeian import FILE, DIR, PATH, Print, Color as c
from toml import get_meta

p = Print()

#----------------------------------------------------------------------------------------- Analysis

def _pyproject(root:str) -> dict:
  """`pyproject.toml` as a dict, empty when there is none to read."""
  path = PATH.join(root, "pyproject.toml")
  if not FILE.exists(path): return {}
  try: return tomllib.loads(str(FILE.load(path)))
  except Exception: return {}

def _requires(root:str) -> str:
  """Every dependency the project declares, required and optional alike, one lowercase blob."""
  project = _pyproject(root).get("project", {})
  names = list(project.get("dependencies", []))
  for group in project.get("optional-dependencies", {}).values(): names += group
  return " ".join(names).lower()

def floor(root:str, pkg_dir:str) -> str:
  """
  The lowest Python the project supports.

  `pyproject.toml` wins, because that is where pip reads it and where a package not built
  by `toml.py` declares it. Falling back on `__init__.py` keeps the packages that are.
  """
  declared = _pyproject(root).get("project", {}).get("requires-python", "")
  return (declared or get_meta(pkg_dir)["python"]).replace(">=", "").replace(">", "").strip()

NEWEST = "3.14"
"""Newest Python the workflows cover. One line to bump when the next one ships."""

def pythons(floor:str) -> list[str]:
  """
  The minor versions CI runs, from the package floor in `requires-python` up to `NEWEST`.

  The ceiling is stated, not read from the interpreter running this.
  A file that changed with the machine writing it could never be held against the commit.
  """
  low, high = int(floor.split(".")[1]), int(NEWEST.split(".")[1])
  return [f"3.{n}" for n in range(low, high + 1)]

@dataclass(frozen=True)
class Project:
  """What the tree says about itself, read once and handed to both generators."""
  name: str
  pythons: list[str]
  cairo: bool
  services: list[str]
  extra: str
  typed: bool
  tests: bool

def scan(pkg_dir:str) -> Project:
  """
  Read the facts the workflows depend on out of the package and its `pyproject.toml`.

  Nothing here is guessed: a server starts because a driver is declared, Cairo is installed
  because `svglib` is, `mypy` runs because the package publishes its annotations, and the
  suite runs because there is a `tests/` to run.
  """
  root = PATH.dirname(pkg_dir)
  deps = _requires(root)
  extras = _pyproject(root).get("project", {}).get("optional-dependencies", {})
  services = []
  if any(d in deps for d in ("psycopg2", "asyncpg")): services.append("postgres")
  if any(d in deps for d in ("pymysql", "aiomysql")): services.append("mysql")
  return Project(
    name=PATH.basename(pkg_dir),
    pythons=pythons(floor(root, pkg_dir)),
    cairo="svglib" in deps,
    services=services,
    extra="[all]" if "all" in extras else "",
    typed=FILE.exists(PATH.join(pkg_dir, "py.typed")),
    tests=DIR.exists(PATH.join(root, "tests")),
  )

#----------------------------------------------------------------------------------------- Generate

HEADER = "# Generated by workflow.py\n\n"

SERVICE = {
  "postgres": """      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: ci
        ports: ["5432:5432"]
        options: >-
          --health-cmd=pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
""",
  "mysql": """      mysql:
        image: mariadb:12
        env:
          MARIADB_ROOT_PASSWORD: ci
        ports: ["3306:3306"]
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
""",
}

def verify_block(project:Project) -> str:
  """
  How a built wheel is proven, as far as the repo allows.

  With a suite, the artifact under test is the wheel: the tests are copied away from the
  source tree so `import` can only answer from site-packages. Without one, installing it is
  still worth doing, because a wheel that cannot be installed is a wheel nobody can use.
  """
  if not project.tests:
    return f'      - run: pip install "$(echo dist/*.whl){project.extra}"\n'
  typing = " mypy" if project.typed else "" # the published annotations, checked once
  return (
    f'      - run: pip install pytest{typing} "$(echo dist/*.whl){project.extra}"\n'
    "      # pyproject carries the pytest config; no source tree beside it, so the wheel answers\n"
    "      - run: mkdir /tmp/t && cp -r tests pyproject.toml /tmp/t/\n"
    "      - run: cd /tmp/t && python -m pytest tests\n"
  )

def services_block(project:Project) -> str:
  """The service containers and the passwords the suite reads, empty when none apply."""
  if not project.services: return ""
  env = project.name.upper()
  containers = "".join(SERVICE[s] for s in project.services)
  reads = "".join(f"      {env}_TEST_{s.upper()}: ci\n" for s in project.services)
  return (
    "    # service containers are a Linux-runner feature, so the live tests belong here\n"
    f"    services:\n{containers}"
    "    env:\n"
    "      # the suite reads these; unset, it skips whatever needs a server\n"
    f"{reads}"
  )

def generate_ci(project:Project) -> str:
  """The gate: every pull request, every push to main, and every release before it ships."""
  every = ", ".join(f'"{v}"' for v in project.pythons)
  ends = ", ".join(f'"{v}"' for v in dict.fromkeys([project.pythons[0], project.pythons[-1]]))
  matrix_python = "${{ matrix.python }}"
  pytest = "pytest " if project.tests else ""
  install = f'pip install {pytest}".{project.extra}"'
  suite = "      - run: python -m pytest tests -q\n" if project.tests else ""
  return HEADER + f"""name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_call: # publish.yml calls this, so a release re-runs every gate before it ships

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python: [{every}]
{services_block(project)}    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: {matrix_python}
      - run: {install}
{suite}
  windows:
    runs-on: windows-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python: [{ends}] # the ends of the range: the middle is covered on Linux
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: {matrix_python}
      - run: {install}
      # no server here, so whatever needs one skips itself
{suite}
  wheel:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "{project.pythons[0]}"
      - run: pip install build
      - run: python -m build
{verify_block(project)}"""

def generate_publish(project:Project, ci:bool=False) -> str:
  """Publishing over OIDC. With `ci`, it waits for the gate instead of shipping unchecked."""
  gate = "  ci:\n    uses: ./.github/workflows/ci.yml\n\n" if ci else ""
  needs = "    needs: ci\n" if ci else ""
  cairo_step = (
    "      - run: sudo apt-get update && "
    "sudo apt-get install -y libcairo2-dev pkg-config python3-dev\n"
  ) if project.cairo else ""
  return HEADER + f"""name: Publish PyPI

on:
  release:
    types: [published]

jobs:
{gate}  publish:
{needs}    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "{project.pythons[0]}"
{cairo_step}      - run: pip install build
      - run: python -m build
{verify_block(project)}      - uses: pypa/gh-action-pypi-publish@release/v1
"""

#------------------------------------------------------------------------------------------- Public

def generate(package:str, folder:str|None=None, ci:bool=False) -> None:
  """
  Write `publish.yml` for `package` into `folder`, default `.github/workflows`.

  Args:
    package: Package directory path.
    ci: Also write `ci.yml` and make publishing wait for it. Not every repo wants a gate.
  """
  pkg_dir = PATH.resolve(package)
  if not DIR.exists(pkg_dir):
    p.err(f"{c.ORANGE}{pkg_dir}{c.END} is not a directory")
    sys.exit(1)
  project = scan(pkg_dir)
  repo = get_meta(pkg_dir)["repo"]
  p.inf(f"Python: {c.TURQUS}{', '.join(project.pythons)}{c.END}")
  if repo:
    p.gap(f"https://github.com/{c.SKY}{repo}{c.END}")
  if project.cairo:
    p.inf(f"Cairo: {c.VIOLET}libcairo2-dev{c.GREY} (svglib detected){c.END}")
  if project.services:
    p.inf(f"Servers: {c.VIOLET}{', '.join(project.services)}{c.GREY} (drivers detected){c.END}")
  if project.typed:
    p.inf(f"Types: {c.VIOLET}mypy{c.GREY} (py.typed detected){c.END}")
  out = folder or PATH.join(PATH.dirname(pkg_dir), ".github", "workflows")
  written = {"publish.yml": generate_publish(project, ci)}
  if ci: written["ci.yml"] = generate_ci(project)
  for file, text in written.items():
    FILE.save(PATH.join(out, file), text)
    p.ok(f"Generated {c.GREY}{out}/{c.END}{c.ORANGE}{file}{c.END}")

#---------------------------------------------------------------------------------------------- CLI

EXAMPLES = """
examples:
  py workflow.py xaeian              Just publish.yml
  py workflow.py xaeian --ci         Add ci.yml and gate publishing on it
  py workflow.py xaeian -o .github   Custom output folder
"""

if __name__ == "__main__":
  from xaeian.cli.args import make_parser, add_help
  parser = make_parser("Generate the GitHub Actions workflows for a package", EXAMPLES)
  parser.add_argument("package", metavar="PACKAGE", help="Package directory to scan")
  parser.add_argument("-o", "--output", default=None, metavar="DIR",
    help="Output folder (default: .github/workflows)")
  parser.add_argument("--ci", action="store_true",
    help="Also write ci.yml and make publishing wait for it")
  add_help(parser)
  args = parser.parse_args()
  generate(args.package, args.output, args.ci)
